#!/bin/bash

# Copyright (C) 2014 Marek Černoch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ $# = 1 ] && [ $1 = "--help" ]; then
  echo  "Toolbox is a command line utility to set binaries directory for tool"\
  echo  "Synopsis"
  echo  "  $0 (to print active toolbox name)"
  echo  "  -- OR --"
  echo  "  $0 new-toolbox (to set active toolbox)"
  echo  "  -- OR --"
  echo  "  $0 --help (to print this)"
  exit 0;
fi

if [ -z "$TOOLS_PATH" ]; then
  echo "Warning: variable TOOLS_DIR was not set, using default (~/tools)"
  echo "Tip: you can place 'export TOOLS_PATH=\"/path/to/tools/dir\"' into "\
       "your ~/.bashrc or ~/.bash_profile to suppress this warning"
  TOOLS_DIR="~/tools";
fi

if [ $# = 0 ]; then
  echo "Toolbox in use: "$(cat $TOOLS_PATH/.config);
else
  echo $1 >$TOOLS_PATH/.config;
fi
